[package]
name = "exercism-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
time = "0.3.41"
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
regex = "1.11.1"
once_cell = "1.21.3"