mod armstrong_numbers;
mod bottle_song;
mod difference_of_squares;
pub mod reverse_string;
pub mod start_gigasecond;
mod grains;
mod leap;
mod nth_prime;
mod prime_factors;
mod proverb;
mod raindrop;
mod sum_of_multiples;
mod bob;
mod high_scores;
mod matching_brackets;
mod collatz_conjecture;
mod series;
mod clock;
mod anagram;
mod space_age;
mod sublist;
